import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import { randomUUID } from 'node:crypto';
import { PrismaClient, Prisma } from '../prisma/client/index.js';
import { createApp } from '../server/app.js';
import { readConfig } from '../server/config.js';
const url = new URL(process.env.TEST_DATABASE_URL);
if (!['localhost','127.0.0.1'].includes(url.hostname) || url.pathname !== '/invictus_test') throw new Error('Solo invictus_test local');
const db = new PrismaClient({ datasources: { db: { url: url.href } } });
const origin = 'http://localhost:5173';
const app = await createApp({ database: db, Prisma, config: readConfig({ ...process.env, DATABASE_URL: url.href, NODE_ENV: 'test', STORAGE_DRIVER: 'local', WEB_ORIGINS: origin, UPLOAD_DIRECTORY: '.local/test-uploads' }) });
test.after(() => db.$disconnect());
const send = (a, method, path, body = {}) => a[method]('/api' + path).set('Origin',origin).send(body);
async function account(role = 'USER') {
  const agent = request.agent(app);
  const { body } = await send(agent,'post','/auth/register',{ username: 'test_' + randomUUID().replaceAll('-', '').slice(0,24), email: `${randomUUID()}@example.test`, password: 'Invictus-Test-2026!' }).expect(201);
  if (role !== 'USER') await db.user.update({ where: { id: body.user.id }, data: { role } });
  return { agent, user: body.user };
}
async function proof(actor, visibility = 'private') {
  return (await actor.agent.post('/api/files').set('Origin',origin).set('Content-Type','image/png').set('X-File-Name','proof.png').set('X-File-Visibility',visibility)
    .send(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jA1sAAAAASUVORK5CYII=','base64')).expect(201)).body.file.id;
}
test('piloto: una categoría, cupos concurrentes, snapshots, observar/corregir/aceptar, rechazo y aislamiento', async () => {
  const owner = await account(), admin = await account(), member = await account(), a = await account(), b = await account(), moderator = await account('ADMIN');
  const team = (await send(owner.agent,'post','/teams',{ name: 'Team piloto' }).expect(201)).body;
  const coadmin = (await send(owner.agent,'post',`/teams/${team.id}/members`,{ email: admin.user.email, role: 'ADMIN' }).expect(201)).body;
  await send(owner.agent,'post',`/teams/${team.id}/members`,{ email: member.user.email, role: 'MEMBER' }).expect(201);
  const qrFileId = await proof(owner);
  const methodData = { type: 'YAPE', label: 'Yape original', phone: '999111222', holderName: 'Tesorería', qrFileId };
  const method = (await send(owner.agent,'post',`/teams/${team.id}/payment-methods`,methodData).expect(201)).body;
  const cash = (await send(owner.agent,'post',`/teams/${team.id}/payment-methods`,{ type: 'CASH', label: 'Efectivo', instructions: 'En oficina' }).expect(201)).body;
  const transfer = (await send(owner.agent,'post',`/teams/${team.id}/payment-methods`,{ type: 'BANK_TRANSFER', label: 'Transferencia', holderName: 'Tesorería', bank: 'Banco', accountNumber: '123456', currency: 'USD' }).expect(201)).body;
  const discipline = (await request(app).get('/api/disciplines').expect(200)).body[0];
  const event = (await send(owner.agent,'post','/events/mine',{ teamId: team.id, disciplineId: discipline.id, title: 'Piloto por categorías', description: 'Prueba de inscripción', startsAt: '2027-09-01T14:00:00Z', timeZone: 'America/Lima', venue: 'Callao', maxCapacity: 5 }).expect(201)).body;
  const category = (await send(owner.agent,'post',`/events/${event.id}/categories`,{ name: 'Adultos', priceCents: 5000, currency: 'PEN', capacity: 1, gender: 'FEMALE', minAge: 18, maxAge: 60 }).expect(201)).body;
  const free = (await send(owner.agent,'post',`/events/${event.id}/categories`,{ name: 'Libre', priceCents: 0 }).expect(201)).body;
  const dollars = (await send(owner.agent,'post',`/events/${event.id}/categories`,{ name: 'USD', priceCents: 1000, currency: 'USD' }).expect(201)).body;
  const cashCategory = (await send(owner.agent,'post',`/events/${event.id}/categories`,{ name: 'Efectivo', priceCents: 1000, currency: 'PEN' }).expect(201)).body;
  await send(owner.agent,'put',`/events/${event.id}/payment-methods`,{ methodIds: [method.id,cash.id,transfer.id] }).expect(200);
  await send(owner.agent,'post',`/events/mine/${event.id}/submit`).expect(200);
  await send(moderator.agent,'post',`/events/manage/${event.id}/review`,{ decision: 'APPROVE' }).expect(200);
  await request(app).get(`/api/events/${event.id}/registration-options`).expect(401);
  await a.agent.get(`/api/events/${event.id}/payment-methods/${method.id}/qr`).expect(200);
  const participant = { birthDate: '2000-09-01', gender: 'FEMALE', phone: '999000111' };
  const proofA = await proof(a), proofB = await proof(b);
  const input = { categoryId: category.id, methodId: method.id, participant, proofFileId: proofA };
  await send(a.agent,'post',`/events/${event.id}/register`,{ ...input, amountCents: 1 }).expect(400);
  await send(a.agent,'post',`/events/${event.id}/register`,{ ...input, participant: { ...participant,birthDate: '2009-09-02' } }).expect(400);
  await send(a.agent,'post',`/events/${event.id}/register`,{ ...input, participant: { ...participant,gender: 'MALE' } }).expect(400);
  await send(a.agent,'post',`/events/${event.id}/register`,{ ...input, proofFileId: proofB }).expect(400);
  await send(a.agent,'post',`/events/${event.id}/register`,{ ...input, proofFileId: await proof(a,'public') }).expect(400);
  assert.equal(await db.eventRegistration.count({ where: { eventId: event.id } }),0);
  const concurrent = await Promise.all([send(a.agent,'post',`/events/${event.id}/register`,input),send(b.agent,'post',`/events/${event.id}/register`,{ ...input,proofFileId: proofB })]);
  assert.deepEqual(concurrent.map(r => r.status).sort(),[201,409]);
  const winner = concurrent[0].status === 201 ? a : b, loser = winner === a ? b : a;
  let r = concurrent.find(r => r.status === 201).body;
  assert.equal(r.status,'PENDING_REVIEW'); assert.equal(r.amountCents,5000);
  assert.equal((await send(winner.agent,'post',`/events/${event.id}/register`,{ ...input,proofFileId: winner === a ? proofA : proofB }).expect(201)).body.id,r.id);
  await send(winner.agent,'post',`/events/${event.id}/register`,{ categoryId: free.id,participant }).expect(409);
  const original = (await db.paymentOperation.findUnique({ where: { id: r.id } })).instructions;
  await send(owner.agent,'put',`/teams/${team.id}/payment-methods/${method.id}`,{ ...methodData,phone: '999333444',label: 'Cuenta cambiada',qrFileId: null }).expect(200);
  assert.deepEqual((await db.paymentOperation.findUnique({ where: { id: r.id } })).instructions,original);
  await send(owner.agent,'delete',`/files/${qrFileId}`).expect(409);
  let detail = (await winner.agent.get(`/api/registrations/${r.id}`).expect(200)).body;
  const paymentId = detail.payments[0].id, proofPath = `/api/registrations/${r.id}/payments/${paymentId}/proof`;
  await admin.agent.get(proofPath).expect(200); await loser.agent.get(proofPath).expect(404);
  await member.agent.get(proofPath).expect(403); await moderator.agent.get(proofPath).expect(404);
  await send(member.agent,'post',`/registrations/${r.id}/review`,{ version: r.version,decision: 'CONFIRMED' }).expect(403);
  r = (await send(admin.agent,'post',`/registrations/${r.id}/review`,{ version: r.version,decision: 'OBSERVED',note: 'Adjunta comprobante legible' }).expect(200)).body;
  assert.equal(r.status,'OBSERVED');
  await send(loser.agent,'post',`/events/${event.id}/register`,{ ...input,proofFileId: loser === a ? proofA : proofB }).expect(409);
  await send(winner.agent,'post',`/registrations/${r.id}/resubmit`,{ version: r.version,participant,proofFileId: winner === a ? proofA : proofB }).expect(409);
  r = (await send(winner.agent,'post',`/registrations/${r.id}/resubmit`,{ version: r.version,participant,proofFileId: await proof(winner) }).expect(200)).body;
  await send(admin.agent,'post',`/registrations/${r.id}/review`,{ version: r.version-1,decision: 'CONFIRMED' }).expect(409);
  const decisions = await Promise.all(['CONFIRMED','CONFIRMED'].map(decision => send(admin.agent,'post',`/registrations/${r.id}/review`,{ version: r.version,decision,note: 'Revisión' })));
  assert.deepEqual(decisions.map(r => r.status).sort(),[200,409]);
  r = decisions.find(r => r.status === 200).body;
  assert.equal(r.status,'CONFIRMED');
  detail = (await winner.agent.get(`/api/registrations/${r.id}`).expect(200)).body;
  assert.equal(detail.payments.length,2); assert.equal(detail.audits.length,4);
  assert.equal((await db.paymentOperation.findUnique({ where: { id: r.id } })).acceptingPayments,false);
  if (r.status === 'CONFIRMED') assert.ok(r.participationCode);
  await send(owner.agent,'delete',`/teams/${team.id}/members/${coadmin.id}`).expect(204);
  await admin.agent.get(proofPath).expect(404);
  // Free registrations are also reviewed; observed retries retain their original category.
  let fr = (await send(loser.agent,'post',`/events/${event.id}/register`,{ categoryId: free.id,participant }).expect(201)).body;
  assert.equal(fr.status,'PENDING_REVIEW'); assert.equal(await db.paymentOperation.findUnique({ where: { id: fr.id } }),null);
  fr = (await send(owner.agent,'post',`/registrations/${fr.id}/review`,{ version: fr.version,decision: 'OBSERVED',note: 'Completa teléfono' }).expect(200)).body;
  fr = (await send(loser.agent,'post',`/registrations/${fr.id}/resubmit`,{ version: fr.version,participant }).expect(200)).body;
  fr = (await send(owner.agent,'post',`/registrations/${fr.id}/review`,{ version: fr.version,decision: 'CONFIRMED' }).expect(200)).body;
  assert.ok(fr.participationCode);
  // Transfer payments reuse the same operation/attempt/result circuit.
  let tr = (await send(member.agent,'post',`/events/${event.id}/register`,{ categoryId: dollars.id,methodId: transfer.id,participant,proofFileId: await proof(member) }).expect(201)).body;
  tr = (await send(owner.agent,'post',`/registrations/${tr.id}/review`,{ version: tr.version,decision: 'REJECTED',note: 'Pago no recibido' }).expect(200)).body;
  assert.equal(tr.status,'REJECTED');
  const cr = (await send(admin.agent,'post',`/events/${event.id}/register`,{ categoryId: cashCategory.id,methodId: cash.id,participant }).expect(201)).body;
  assert.equal(cr.status,'PENDING_REVIEW');
  await send(owner.agent,'post',`/registrations/${cr.id}/review`,{ version: cr.version,decision: 'CONFIRMED' }).expect(200);
  await send(member.agent,'post',`/registrations/${tr.id}/resubmit`,{ version: tr.version,participant,proofFileId: await proof(member) }).expect(409);
  const list = (await owner.agent.get(`/api/events/${event.id}/registrations?status=CONFIRMED`).expect(200)).body;
  assert.ok(list.items.every(i => i.status === 'CONFIRMED')); assert.ok(list.summary.occupied >= 1);
  const history = (await loser.agent.get('/api/profile/registrations').expect(200)).body.find(x => x.id === fr.id);
  assert.equal(history.categorySnapshot.name,'Libre');
});


test('evento personal: Yape/Plin, QR privado, pago pendiente, confirmación y aislamiento sin Team',async()=>{
 const owner=await account(), outsider=await account(), participant=await account(), freeParticipant=await account();
 await send(owner.agent,'put','/profile',{name:'Ana',lastName:'Pérez',documentType:'DNI',documentNumber:'12345678',phone:'+51987654321'}).expect(200);
 const discipline=(await request(app).get('/api/disciplines').expect(200)).body[0];
 const input={title:'Personal con pagos',description:'Encuentro independiente',startsAt:'2027-10-02T14:00:00Z',timeZone:'America/Lima',venue:'Lima',maxCapacity:5,disciplineId:discipline.id};
 const event=(await send(owner.agent,'post','/events/mine',input).expect(201)).body;
 const other=(await send(owner.agent,'post','/events/mine',{...input,title:'Otro evento'}).expect(201)).body;
 const path='/events/'+event.id+'/payment-methods';
 const category=(await send(owner.agent,'post','/events/'+event.id+'/categories',{name:'5K',modality:'5 km',priceCents:2500,capacity:2}).expect(201)).body;
 const free=(await send(owner.agent,'post','/events/'+event.id+'/categories',{name:'Invitados',priceCents:0}).expect(201)).body;
 await send(owner.agent,'post','/events/'+event.id+'/categories',{name:'USD',priceCents:1000,currency:'USD'}).expect(400);
 await send(owner.agent,'post','/events/mine/'+event.id+'/publish').expect(409);
 const qrFileId=await proof(owner);
 const yapeData={type:'YAPE',label:'Yape personal',phone:'987654321',holderName:'Ana Pérez',qrFileId};
 await send(outsider.agent,'post',path,yapeData).expect(403);
 await send(owner.agent,'post',path,{...yapeData,type:'CASH',instructions:'En oficina'}).expect(400);
 await send(owner.agent,'post',path,{...yapeData,currency:'USD'}).expect(400);
 await send(owner.agent,'post',path,{...yapeData,qrFileId:await proof(outsider)}).expect(404);
 const yape=(await send(owner.agent,'post',path,yapeData).expect(201)).body;
 const plin=(await send(owner.agent,'post',path,{...yapeData,type:'PLIN',label:'Plin personal',qrFileId:null}).expect(201)).body;
 assert.equal(yape.teamId,null);assert.equal(yape.eventId,event.id);
 const configuration=await db.eventRegistrationConfig.findUnique({where:{eventId:event.id}});assert.ok(configuration.paymentRecipientId);
 await send(owner.agent,'patch','/events/mine/'+event.id,{...input,maxCapacity:6}).expect(200);
 assert.equal((await db.eventRegistrationConfig.findUnique({where:{eventId:event.id}})).paymentRecipientId,configuration.paymentRecipientId);
 await send(owner.agent,'put','/events/'+other.id+'/payment-methods',{methodIds:[yape.id]}).expect(400);
 await assert.rejects(db.eventPaymentMethod.create({data:{eventId:other.id,methodId:yape.id,teamId:null}}));
 await send(owner.agent,'post','/events/mine/'+event.id+'/publish').expect(200);
 await owner.agent.get('/api/events/'+event.id+'/setup').expect(200);
 const options=(await participant.agent.get('/api/events/'+event.id+'/registration-options').expect(200)).body;
 assert.equal(options.methods.length,2);assert.ok(options.methods.some(m=>m.id===plin.id));
 await participant.agent.get('/api/events/'+event.id+'/payment-methods/'+yape.id+'/qr').expect(200);
 await request(app).get('/api/files/'+qrFileId+'/public').expect(404);
 const participantData={phone:'999111222'};
 await send(participant.agent,'post','/events/'+event.id+'/register',{categoryId:category.id,methodId:yape.id,participant:participantData}).expect(400);
 assert.equal(await db.eventRegistration.count({where:{eventId:event.id}}),0);
 const registration=(await send(participant.agent,'post','/events/'+event.id+'/register',{categoryId:category.id,methodId:plin.id,participant:participantData,proofFileId:await proof(participant)}).expect(201)).body;
 assert.equal(registration.status,'PENDING_REVIEW');assert.equal(registration.amountCents,2500);assert.equal(registration.paymentInstructionsSnapshot.type,'PLIN');
 const operation=await db.paymentOperation.findUnique({where:{id:registration.id}});assert.equal(operation.recipientId,configuration.paymentRecipientId);
 const detail=(await owner.agent.get('/api/registrations/'+registration.id).expect(200)).body;
 const proofPath='/api/registrations/'+registration.id+'/payments/'+detail.payments[0].id+'/proof';
 await owner.agent.get(proofPath).expect(200);await outsider.agent.get(proofPath).expect(403);
 await send(outsider.agent,'post','/registrations/'+registration.id+'/review',{version:registration.version,decision:'CONFIRMED'}).expect(403);
 const confirmed=(await send(owner.agent,'post','/registrations/'+registration.id+'/review',{version:registration.version,decision:'CONFIRMED'}).expect(200)).body;
 assert.equal(confirmed.status,'CONFIRMED');
 await send(owner.agent,'post','/events/mine/'+event.id+'/unpublish').expect(200);
 await send(owner.agent,'put',path+'/'+yape.id,{...yapeData,phone:'999000111'}).expect(409);
 await send(owner.agent,'put','/events/'+event.id+'/categories/'+category.id,{name:'5K',priceCents:1}).expect(409);
 await send(owner.agent,'post','/events/mine/'+event.id+'/publish').expect(200);
 const freeRegistration=(await send(freeParticipant.agent,'post','/events/'+event.id+'/register',{categoryId:free.id,participant:participantData}).expect(201)).body;
 assert.equal(freeRegistration.status,'PENDING_REVIEW');assert.equal(await db.paymentOperation.findUnique({where:{id:freeRegistration.id}}),null);
 assert.deepEqual((await db.paymentOperation.findUnique({where:{id:registration.id}})).instructions,operation.instructions);
 assert.equal(await db.teamMember.count({where:{userId:owner.user.id}}),0);
});
