import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import { randomUUID } from 'node:crypto';
import { PrismaClient, Prisma } from '../prisma/client/index.js';
import { createApp } from '../server/app.js';
import { readConfig } from '../server/config.js';
const url = new URL(process.env.TEST_DATABASE_URL);
if (!['localhost', '127.0.0.1'].includes(url.hostname) || url.pathname !== '/invictus_test') throw new Error('Solo invictus_test local');
const db = new PrismaClient({ datasources: { db: { url: url.href } } });
const origin = 'http://localhost:5173';
const app = await createApp({ database: db, Prisma, config: readConfig({ ...process.env, DATABASE_URL: url.href, NODE_ENV: 'test', STORAGE_DRIVER: 'local', WEB_ORIGINS: origin, UPLOAD_DIRECTORY: '.local/test-uploads' }) });
test.after(() => db.$disconnect());
const send = (a, method, path, body = {}) => a[method]('/api' + path).set('Origin', origin).send(body);
async function account(role = 'USER') {
  const agent = request.agent(app);
  const { body } = await send(agent, 'post', '/auth/register', { name: 'Setup', lastName: 'Team', email: `${randomUUID()}@example.test`, password: 'Invictus-Test-2026!' }).expect(201);
  if (role !== 'USER') await db.user.update({ where: { id: body.user.id }, data: { role } });
  return { agent, user: body.user };
}
test('configuración: permisos, aislamiento, QR privado, moneda y publicación compatible', async () => {
  const owner = await account(), admin = await account(), outsider = await account(), moderator = await account('ADMIN');
  const catalog = (await request(app).get('/api/disciplines').expect(200)).body;
  await request(app).get('/api/events').expect(200);
  const team = (await send(owner.agent, 'post', '/teams', { name: 'Configuración' }).expect(201)).body;
  const other = (await send(outsider.agent, 'post', '/teams', { name: 'Otro' }).expect(201)).body;
  await send(owner.agent, 'post', `/teams/${team.id}/members`, { email: admin.user.email, role: 'ADMIN' }).expect(201);
  const methodPath = `/teams/${team.id}/payment-methods`;
  const yape = { type: 'YAPE', label: 'Tesorería', phone: '999123456', holderName: 'Titular', currency: 'PEN' };
  await send(admin.agent, 'post', methodPath, yape).expect(403);
  await send(moderator.agent, 'post', methodPath, yape).expect(404);
  await send(owner.agent, 'post', methodPath, { ...yape, currency: 'USD' }).expect(400);
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jA1sAAAAASUVORK5CYII=', 'base64');
  const file = (await owner.agent.post('/api/files').set('Origin', origin).set('Content-Type', 'image/png').set('X-File-Name', 'qr.png').set('X-File-Visibility', 'private').send(png).expect(201)).body.file;
  const method = (await send(owner.agent, 'post', methodPath, { ...yape, qrFileId: file.id }).expect(201)).body;
  await send(owner.agent, 'post', methodPath, { ...yape, label: 'Segundo Yape' }).expect(201);
  const recipient = (await db.team.findUnique({ where: { id: team.id } })).paymentRecipientId;
  assert.ok(recipient);
  await admin.agent.get(`/api${methodPath}/${method.id}/qr`).expect(200);
  await outsider.agent.get(`/api${methodPath}/${method.id}/qr`).expect(404);
  await request(app).get(`/api/files/${file.id}/public`).expect(404);
  await send(owner.agent, 'delete', `/files/${file.id}`).expect(409);
  const foreignMethod = (await send(outsider.agent, 'post', `/teams/${other.id}/payment-methods`, yape).expect(201)).body;
  const event = (await send(admin.agent, 'post', '/events/mine', { teamId: team.id, disciplineId: catalog[0].id, title: 'Evento categorías', description: 'Evento de prueba', startsAt: '2027-09-01T14:00:00Z', timeZone: 'America/Lima', venue: 'Callao', maxCapacity: 5 }).expect(201)).body;
  assert.equal(event.disciplineId, catalog[0].id);
  const category = { name: 'Adultos', priceCents: 5000, currency: 'PEN', minAge: 18, capacity: 3 };
  await send(outsider.agent, 'post', `/events/${event.id}/categories`, category).expect(404);
  await send(admin.agent, 'post', `/events/${event.id}/categories`, { ...category, maxAge: 10 }).expect(400);
  const saved = (await send(admin.agent, 'post', `/events/${event.id}/categories`, category).expect(201)).body;
  await send(admin.agent, 'post', `/events/${event.id}/categories`, category).expect(409);
  await send(admin.agent, 'put', `/events/${event.id}/payment-methods`, { methodIds: [foreignMethod.id] }).expect(400);
  await assert.rejects(db.eventPaymentMethod.create({ data: { eventId: event.id, teamId: team.id, methodId: foreignMethod.id } }));
  await send(admin.agent, 'post', `/events/mine/${event.id}/submit`).expect(409);
  await send(admin.agent, 'put', `/events/${event.id}/payment-methods`, { methodIds: [method.id] }).expect(200);
  const proposal = (await moderator.agent.get(`/api/events/${event.id}/setup`).expect(200)).body;
  assert.equal(proposal.editable, false); assert.equal(proposal.methods.length, 1); assert.equal(proposal.methods[0].phone, undefined);
  await send(moderator.agent, 'put', `/events/${event.id}/categories/${saved.id}`, category).expect(404);
  await send(admin.agent, 'post', `/events/mine/${event.id}/submit`).expect(200);
  await send(admin.agent, 'put', `/events/${event.id}/categories/${saved.id}`, category).expect(409);
  await send(moderator.agent, 'post', `/events/manage/${event.id}/review`, { decision: 'APPROVE' }).expect(200);
  const publicEvent = (await request(app).get(`/api/events/public/${event.publicSlug}`).expect(200)).body;
  assert.equal(publicEvent.categories[0].priceCents, 5000); assert.equal(publicEvent.categories.length, 1);
  assert.equal(publicEvent.enabledPaymentMethods, undefined);
  await send(outsider.agent, 'post', `/events/${event.id}/register`).expect(400);
  assert.equal(await db.eventRegistration.count({ where: { eventId: event.id } }), 0);
  await send(owner.agent, 'put', `${methodPath}/${method.id}`, { ...yape, active: false, qrFileId: file.id }).expect(200);
  assert.equal((await db.team.findUnique({ where: { id: team.id } })).paymentRecipientId, recipient);
});
