import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import { randomUUID } from 'node:crypto';
import { PrismaClient,Prisma } from '../prisma/client/index.js';
import { createApp } from '../server/app.js';
import { readConfig } from '../server/config.js';
const url=new URL(process.env.TEST_DATABASE_URL);if(!['localhost','127.0.0.1'].includes(url.hostname)||url.pathname!=='/invictus_test')throw new Error('Solo invictus_test local');
const db=new PrismaClient({datasources:{db:{url:url.href}}});
const recipientId=randomUUID();const origin='http://localhost:5173';
const config=readConfig({...process.env,DATABASE_URL:url.href,NODE_ENV:'test',PAYMENT_RECIPIENT_ID:recipientId,UPLOAD_DIRECTORY:'.local/test-uploads',PAYMENT_METHODS:'cash,yape',WEB_ORIGINS:origin});
const app=await createApp({database:db,Prisma,config});
test.after(()=>db.$disconnect());
const post=(agent,path,body)=>agent.post('/api'+path).set('Origin',origin).send(body);
const patch=(agent,path,body)=>agent.patch('/api'+path).set('Origin',origin).send(body);
async function account(role='USER'){const agent=request.agent(app);const email=`invictus-test-${randomUUID()}@example.test`;const password='Invictus-Test-2026!';const r=await post(agent,'/auth/register',{name:'Prueba',lastName:'Invictus',email,password}).expect(201);if(role!=='USER')await db.user.update({where:{id:r.body.user.id},data:{role}});await post(agent,'/auth/logout',{}).expect(204);const login=await post(agent,'/auth/login',{email,password}).expect(200);assert.ok(login.headers['set-cookie']);await agent.get('/api/auth/session').expect(200);return {agent,user:login.body.user};}
test('integración real: identidad, cupos, stock, pagos, cotización y archivos',async()=>{
 const admin=await account('ADMIN'),organizer=await account('ORGANIZER'),a=await account(),b=await account();
 await db.paymentRecipient.create({data:{id:recipientId,name:'Invictus TEST',phone:'999111222',holder:'Prueba'}});await db.recipientMember.create({data:{recipientId,userId:admin.user.id,manage:true,review:true}});
 await post(a.agent,'/events/manage',{title:'No autorizado'}).expect(403);
 const team=(await post(organizer.agent,'/teams',{name:'Team de integración'}).expect(201)).body;
 const event=(await post(organizer.agent,'/events/mine',{teamId:team.id,title:'EVENTO TEST '+randomUUID(),description:'Evento de integración, sin asistencia acreditada.',startsAt:'2027-06-20T14:00:00Z',timeZone:'America/Lima',venue:'Lima',maxCapacity:1}).expect(201)).body;
 await post(organizer.agent,`/events/manage/${event.id}/publish`,{}).expect(403);
 await post(organizer.agent,`/events/mine/${event.id}/submit`,{}).expect(200);
 await post(admin.agent,`/events/manage/${event.id}/review`,{decision:'APPROVE'}).expect(200);
 await request(app).get('/api/events/public/'+event.publicSlug).expect(200);
 const enrollments=await Promise.all([post(a.agent,`/events/${event.id}/register`,{}),post(b.agent,`/events/${event.id}/register`,{})]);assert.deepEqual(enrollments.map(r=>r.status).sort(),[201,409]);
 const winner=enrollments[0].status===201?a:b;const history=await winner.agent.get('/api/profile/registrations').expect(200);assert.equal(history.body[0].status,'CONFIRMED');assert.equal(history.body[0].event.title,event.title);await winner.agent.get('/api/profile').expect(200);const attendees=await organizer.agent.get(`/api/events/manage/${event.id}/attendees`).expect(200);assert.equal(attendees.body.length,1);
 await patch(organizer.agent,`/events/mine/${event.id}`,{title:event.title,maxCapacity:2}).expect(409);
 const createProduct=async stock=>(await post(admin.agent,'/shop/admin/products',{name:'TROFEO TEST',description:'Existencias físicas de prueba',priceCents:2500,published:true,variants:[{name:'Oro',sku:randomUUID(),stock}]}).expect(200)).body;
 const cart=async(who,p)=>(await post(who.agent,'/shop/cart',{items:[{productId:p.id,variantId:p.variants[0].id,quantity:1}]}).expect(200)).body;
 const p=await createProduct(1),ca=await cart(a,p),cb=await cart(b,p);
 const keys=[randomUUID(),randomUUID()];const orders=await Promise.all([post(a.agent,'/orders',{cartId:ca.cartId,key:keys[0]}),post(b.agent,'/orders',{cartId:cb.cartId,key:keys[1]})]);assert.deepEqual(orders.map(r=>r.status).sort(),[201,409]);
 const idx=orders[0].status===201?0:1;const buyer=idx===0?a:b;const order=orders[idx].body.order;
 assert.equal((await db.shopVariant.findUnique({where:{id:p.variants[0].id}})).stock,0);
 await post(buyer.agent,'/orders',{cartId:idx===0?ca.cartId:cb.cartId,key:keys[idx]}).expect(201);
 const pay=(await post(buyer.agent,`/payments/${order.id}`,{method:'cash',proofFileId:null}).expect(201)).body.payment;
 await patch(buyer.agent,`/payments/admin/${order.id}/${pay.id}`,{status:'verified'}).expect(403);
 await patch(admin.agent,`/payments/admin/${order.id}/${pay.id}`,{status:'verified'}).expect(200);
 await patch(admin.agent,`/orders/admin/${order.id}/status`,{status:'cancelled'}).expect(409);
 await patch(admin.agent,`/orders/admin/${order.id}/status`,{status:'accepted'}).expect(200);
 await patch(admin.agent,`/orders/admin/${order.id}/status`,{status:'completed'}).expect(200);
 const p2=await createProduct(1),c2=await cart(a,p2);const o2=(await post(a.agent,'/orders',{cartId:c2.cartId,key:randomUUID()}).expect(201)).body.order;
 for(let i=0;i<2;i++)await patch(admin.agent,`/orders/admin/${o2.id}/status`,{status:'cancelled'}).expect(200);
 assert.equal((await db.shopVariant.findUnique({where:{id:p2.variants[0].id}})).stock,1);
 const quote=await post(request(app),'/quotes',{contactName:'TEST Invictus',email:'quote@example.test',phone:'999111222',quantity:20,requiredDate:'2027-12-01',design:'Medallas personalizadas para evento de prueba'}).expect(201);const list=await admin.agent.get('/api/admin/quotes').expect(200);assert.ok(list.body.some(q=>q.id===quote.body.id));
 const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
 const uploaded=await a.agent.post('/api/files').set('Origin',origin).set('Content-Type','image/png').set('X-File-Name','prueba.png').set('X-File-Visibility','private').send(image).expect(201);
 const id=uploaded.body.file.id;await b.agent.get(`/api/files/${id}/access`).expect(404);await request(app).get(`/api/files/${id}/public`).expect(404);const access=await a.agent.get(`/api/files/${id}/access`).expect(200);await a.agent.get(access.body.url).expect(200);
 await post(a.agent,'/auth/logout',{}).expect(204);await a.agent.get('/api/profile').expect(401);
});

test('eventos personales: propiedad, revisión, correcciones y aprobación',async()=>{
 const a=await account(),b=await account(),admin=await account('ADMIN');
 const team=(await post(a.agent,'/teams',{name:'Team externo'}).expect(201)).body;
 const input={teamId:team.id,title:'Evento externo '+randomUUID(),description:'Evento propuesto por participante',startsAt:'2027-08-01T14:00:00Z',timeZone:'America/Lima',venue:'La Punta',maxCapacity:30};
 const event=(await post(a.agent,'/events/mine',input).expect(201)).body;
 assert.equal(event.source,'EXTERNAL');assert.equal(event.reviewStatus,'DRAFT');
 await request(app).get('/api/events/public/'+event.publicSlug).expect(404);
 await b.agent.get('/api/events/mine/'+event.id).expect(404);
 await patch(b.agent,'/events/mine/'+event.id,input).expect(404);
 await post(b.agent,`/events/mine/${event.id}/submit`,{}).expect(404);
 assert.ok(!(await b.agent.get('/api/events/mine').expect(200)).body.some(e=>e.id===event.id));
 await patch(a.agent,'/events/mine/'+event.id,{...input,status:'PUBLISHED'}).expect(403);
 await post(admin.agent,`/events/manage/${event.id}/publish`,{}).expect(409);
 await post(a.agent,`/events/mine/${event.id}/submit`,{}).expect(200);
 await patch(a.agent,'/events/mine/'+event.id,input).expect(409);
 await post(a.agent,`/events/manage/${event.id}/review`,{decision:'APPROVE'}).expect(403);
 await post(admin.agent,`/events/manage/${event.id}/review`,{decision:'REQUEST_CHANGES'}).expect(400);
 await post(admin.agent,`/events/manage/${event.id}/review`,{decision:'REQUEST_CHANGES',note:'Precisa el punto de encuentro'}).expect(200);
 const returned=(await a.agent.get('/api/events/mine/'+event.id).expect(200)).body;
 assert.equal(returned.reviewNote,'Precisa el punto de encuentro');
 await patch(a.agent,'/events/mine/'+event.id,{...input,venue:'Muelle de La Punta'}).expect(200);
 await post(a.agent,`/events/mine/${event.id}/submit`,{}).expect(200);
 await post(admin.agent,`/events/manage/${event.id}/review`,{decision:'APPROVE'}).expect(200);
 await request(app).get('/api/events/public/'+event.publicSlug).expect(200);
 await patch(a.agent,'/events/mine/'+event.id,input).expect(409);
 await post(a.agent,`/events/${event.id}/register`,{}).expect(201);
 const attendees=(await a.agent.get(`/api/events/mine/${event.id}/attendees`).expect(200)).body;assert.equal(attendees.length,1);assert.equal(attendees[0].participant.id,a.user.id);
 await b.agent.get(`/api/events/mine/${event.id}/attendees`).expect(404);
 await request(app).get(`/api/events/mine/${event.id}/attendees`).expect(401);
 const officialTeam=(await post(admin.agent,'/teams',{name:'Team Invictus'}).expect(201)).body;
 const official=(await post(admin.agent,'/events/manage',{...input,teamId:officialTeam.id}).expect(201)).body;
 assert.equal(official.source,'INVICTUS');
 await post(admin.agent,`/events/manage/${official.id}/publish`,{}).expect(200);
});
