import React,{useState,useEffect}from'react';import{api,upload,fileUrl}from'../services/api.js';import{useData,useAction}from'../hooks/data.js';import{Heading,State,Feedback,Field,Textarea,Records,Status,date,money}from'../components/UI.jsx';
import {Modal} from '../components/Modal.jsx';
import CustomerOrders from './CustomerOrders.jsx';
import {RegistrationDetail,RegistrationStatus} from '../components/CategoryRegistration.jsx';
import {categoryPrice} from '../components/EventSetup.jsx';
export { Login } from './Login.jsx';
export { Account } from './Profile.jsx';
export { Registrations } from './Registrations.jsx';

export function Cart({cart,setCart}){const a=useAction(),[key,setKey]=useState(()=>sessionStorage.getItem('checkout-key')||crypto.randomUUID());async function checkout(){sessionStorage.setItem('checkout-key',key);const r=await api('/orders','POST',{cartId:cart.cartId,key});sessionStorage.removeItem('checkout-key');setKey(crypto.randomUUID());setCart(null);location.hash='/pedidos';return r;}return <><Heading eyebrow="TU SELECCIÓN" title="Carrito de reconocimientos."/><Feedback state={a}/>{!cart?.items?.length?<div className="empty"><p>Tu carrito está vacío.</p><a href="#/tienda" className="button">Explorar la tienda</a></div>:<div className="card"><Records items={cart.items} columns={[{label:'Producto',render:i=>i.name},{label:'Cantidad',render:i=>i.quantity},{label:'Subtotal',render:i=>money(i.lineTotalCents)}]}/><h2>Total: {money(cart.totalCents)}</h2><p>Las existencias se reservan al crear el pedido. El pago se revisa manualmente.</p><div className="actions"><button disabled={a.busy} onClick={()=>a.run(checkout,'Pedido creado.')}>Crear pedido →</button><button className="secondary" disabled={a.busy} onClick={()=>{setCart(null);sessionStorage.removeItem('checkout-key');setKey(crypto.randomUUID())}}>Vaciar carrito</button></div></div>}</>}
export function Orders({admin=false}) { return admin ? <AdminOrders admin/> : <CustomerOrders renderDetail={(order,close)=><OrderDetail key={order.id} order={order} admin={false} close={close}/>}/>; }
function AdminOrders({admin=false}){const r=useData(admin?'/orders/admin':'/orders'),a=useAction(),[selected,setSelected]=useState(null);return <><Heading eyebrow={admin?'ADMINISTRACIÓN':'CUENTA'} title={admin?"Pedidos":"Pedidos"}/><Feedback state={a}/><State resource={r}>{data=><Records items={data.orders} columns={[{label:'Pedido',render:i=>i.id.slice(0,8).toUpperCase()},{label:'Total',render:i=>money(i.totalCents)},{label:'Estado',render:i=><Status value={i.status}/>}]} actions={i=><><button className="secondary" onClick={()=>setSelected(i)}>Ver detalle</button>{admin&&['pending','accepted'].includes(i.status)&&<><button disabled={a.busy} onClick={()=>a.run(async()=>{await api(`/orders/admin/${i.id}/status`,'PATCH',{status:i.status==='pending'?'accepted':'completed'});r.reload();},'Estado actualizado.')}>{i.status==='pending'?'Aceptar':'Completar'}</button><button className="danger" disabled={a.busy} onClick={()=>{if(confirm('¿Cancelar este pedido y restituir sus existencias? Solo se permite sin pago verificado.'))a.run(async()=>{await api(`/orders/admin/${i.id}/status`,'PATCH',{status:'cancelled'});r.reload();},'Pedido cancelado.')}}>Cancelar</button></>}</>}/>}</State>{selected&&<OrderDetail key={selected.id} order={selected} admin={admin} close={()=>setSelected(null)}/>}</>}
function OrderDetail({order,admin,close}){const r=useData('/payments/'+(admin?'admin/':'')+order.id),op=useData('/payments/operations/'+(admin?'admin/':'')+order.id),methods=useData('/payments/methods'),a=useAction();const[method,setMethod]=useState('cash'),[file,setFile]=useState(null);return <section className="card detail"><button className="secondary" onClick={close}>Cerrar detalle</button><h2>Pedido {order.id.slice(0,8).toUpperCase()}</h2>{order.items.map(i=><p key={i.productId}>{i.name} × {i.quantity}</p>)}<State resource={op}>{data=><p>Pago a {data.operation.instructions.recipientName} · {data.operation.instructions.holder} {data.operation.instructions.phone}</p>}</State><State resource={r}>{data=><>{data.payments.map(p=><div className="payment-row" key={p.id}><Status value={p.status}/><span>{money(p.amountCents)} · {p.method}</span>{admin&&['pending','pending_review'].includes(p.status)&&<div className="actions"><button disabled={a.busy} onClick={()=>a.run(async()=>{await api(`/payments/admin/${order.id}/${p.id}`,'PATCH',{status:'verified'});r.reload();},'Pago verificado.')}>Verificar pago</button><button className="danger" disabled={a.busy} onClick={()=>{const reason=prompt('Motivo del rechazo');if(reason)a.run(async()=>{await api(`/payments/admin/${order.id}/${p.id}`,'PATCH',{status:'rejected',reason});r.reload();},'Pago rechazado.')}}>Rechazar</button></div>}{p.proofFileId&&<a className="button secondary" href={`${import.meta.env.VITE_API_URL||'/api'}/payments/${admin?'admin/':''}${order.id}/${p.id}/proof`}>Ver comprobante</a>}</div>)}{!admin&&!['cancelled','completed'].includes(order.status)&&!data.payments.some(p=>p.status!=='rejected')&&<form className="form" onSubmit={e=>{e.preventDefault();a.run(async()=>{const proofFileId=method==='cash'?null:(await upload(file)).id;await api('/payments/'+order.id,'POST',{method,proofFileId});r.reload();},'Pago registrado para revisión.')}}><State resource={methods}>{data=><label>Método de pago<select value={method} onChange={e=>setMethod(e.target.value)}>{data.methods.map(m=><option key={m} value={m}>{m==='cash'?'Efectivo':m}</option>)}</select></label>}</State>{method!=='cash'&&<label>Comprobante privado · imagen o PDF, máximo 10 MB<input type="file" accept="image/png,image/jpeg,image/webp,application/pdf" required onChange={e=>setFile(e.target.files[0])}/></label>}<button disabled={a.busy}>Registrar pago para revisión</button></form>}</>}</State><Feedback state={a}/></section>}
