import React,{useEffect,useRef,useState} from 'react';
import {api,upload} from '../services/api.js';
import {navigate} from '../services/navigation.js';
import {useData,useAction} from '../hooks/data.js';
import {Field,Textarea,Feedback,State,money,Status} from '../components/UI.jsx';
import {ImagePicker} from '../components/ImagePicker.jsx';
import {IconAction} from '../components/IconAction.jsx';
import '../styles/event-editor.css';
const initial={title:'',description:'',venue:'',eventDate:'',departureTime:'',disciplineId:'',maxCapacity:50,primaryImageFileId:null,meetingTime:'',kitEnabled:false,kitDateFrom:'',kitDateTo:'',kitTimeFrom:'',kitTimeTo:'',kitVenue:'',kitInstructions:'',routeImageFileId:null};
const localDate=value=>value?new Date(new Date(value).getTime()-18000000).toISOString().slice(0,16):'';
const isoDate=value=>value?new Date(value+'-05:00').toISOString():null;
export default function EventEditor({id}){
 const disciplines=useData('/disciplines'),action=useAction(),[loaded,setLoaded]=useState(!id),[loadError,setLoadError]=useState('');
 const [event,setEvent]=useState(null),[values,setValues]=useState(initial),[categories,setCategories]=useState([]),[methods,setMethods]=useState([]),[withCategories,setWithCategories]=useState(false),[generalPrice,setGeneralPrice]=useState('0'),[image,setImage]=useState(null),[routeImage,setRouteImage]=useState(null),[hasRegistrations,setHasRegistrations]=useState(false),[editable,setEditable]=useState(true),[step,setStep]=useState(Math.max(1,Math.min(3,Number(new URLSearchParams(location.search).get('paso'))||1))),[dirty,setDirty]=useState(false);
 const dirtyRef=useRef(false);dirtyRef.current=dirty;
 useEffect(()=>{if(!id)return;let active=true;Promise.all([api('/events/mine/'+id),api('/events/'+id+'/setup')]).then(([e,setup])=>{if(!active)return;setEvent(e);setValues({...initial,...e,venue:e.venue||'',description:e.description||'',eventDate:localDate(e.startsAt).slice(0,10),departureTime:localDate(e.startsAt).slice(11,16),meetingTime:localDate(e.meetingAt).slice(11,16),kitDateFrom:e.kitDateFrom?.slice(0,10)||'',kitDateTo:e.kitDateTo?.slice(0,10)||'',kitTimeFrom:e.kitTimeFrom||'',kitTimeTo:e.kitTimeTo||'',kitVenue:[e.kitVenue,e.kitAddress].filter(Boolean).join(' · '),kitInstructions:e.kitInstructions||'',maxCapacity:e.configuration?.maxCapacity||50,disciplineId:e.disciplineId||''});setCategories(setup.categories.map(c=>({...c,key:c.id,price:String(c.priceCents/100)})));setWithCategories(setup.categories.some(c=>c.active && c.name!=='Inscripción general'));setGeneralPrice(String((setup.categories.find(c=>c.name==='Inscripción general')?.priceCents||0)/100));setMethods(setup.methods.map(m=>({...m,key:m.id,enabled:setup.methodIds.includes(m.id)||!m.active,file:null})));setHasRegistrations(setup.hasRegistrations===true);setEditable(setup.editable);setLoaded(true);}).catch(e=>{if(active)setLoadError(e.message);});return()=>{active=false;};},[id]);
 useEffect(()=>{const before=e=>{if(dirtyRef.current){e.preventDefault();e.returnValue='';}};const click=e=>{if(!dirtyRef.current)return;const a=e.target.closest?.('a[href]');if(a&&!a.getAttribute('href').startsWith('#')&&!confirm('Tienes cambios sin guardar. ¿Salir sin guardarlos?')){e.preventDefault();e.stopPropagation();}};const pop=()=>{if(dirtyRef.current&&!confirm('Tienes cambios sin guardar. ¿Salir sin guardarlos?'))navigate(id?'/mis-eventos/'+id+'/editar':'/mis-eventos/nuevo',{replace:true});};window.addEventListener('beforeunload',before);document.addEventListener('click',click,true);window.addEventListener('popstate',pop);return()=>{window.removeEventListener('beforeunload',before);document.removeEventListener('click',click,true);window.removeEventListener('popstate',pop);};},[id]);
 const change=e=>{setValues(v=>({...v,[e.target.name]:e.target.value}));setDirty(true);};
 const updateCategory=(key,patch)=>{setCategories(rows=>rows.map(c=>c.key===key?{...c,...patch}:c));setDirty(true);};
 const updateMethod=(key,patch)=>{setMethods(rows=>rows.map(m=>m.key===key?{...m,...patch}:m));setDirty(true);};
 const activeCategories=withCategories?categories.filter(c=>c.active!==false):[{name:'Inscripción general',price:generalPrice}];
 const paid=activeCategories.some(c=>Number(c.price)>0);
 const startsAt=values.eventDate&&values.departureTime?values.eventDate+'T'+values.departureTime:'';
 const meetingAt=values.eventDate&&values.meetingTime?values.eventDate+'T'+values.meetingTime:'';
 const logisticsMissing=[meetingAt&&startsAt&&meetingAt>startsAt&&'Concentración antes del inicio',values.kitEnabled&&(!values.kitDateFrom||!values.kitDateTo||!values.kitTimeFrom||!values.kitTimeTo||!values.kitVenue.trim())&&'Datos de entrega de kits',values.kitEnabled&&values.kitDateFrom&&values.kitDateTo&&values.kitDateTo<values.kitDateFrom&&'Fecha hasta posterior o igual a fecha desde',values.kitEnabled&&values.kitTimeFrom&&values.kitTimeTo&&values.kitTimeTo<=values.kitTimeFrom&&'Hora hasta posterior a hora desde'].filter(Boolean);
 const missing=[...logisticsMissing,!values.title.trim()&&'Nombre',!values.description.trim()&&'Descripción',(!startsAt||!Number.isFinite(new Date(startsAt+'-05:00').getTime()))?'Fecha del evento y hora de salida':(event?.status!=='PUBLISHED'&&new Date(startsAt+'-05:00')<=new Date()?'Fecha y hora futura':false),!values.venue.trim()&&'Ubicación',(!Number.isInteger(Number(values.maxCapacity))||Number(values.maxCapacity)<1)&&'Cupo válido',activeCategories.some(c=>!Number.isFinite(Number(c.price))||Number(c.price)<0)&&'Precio válido',activeCategories.some(c=>!c.name?.trim())&&'Nombre de categoría',(withCategories||paid)&&!values.disciplineId&&'Disciplina',withCategories&&!activeCategories.length&&'Al menos una categoría',paid&&!methods.some(m=>m.enabled&&m.holderName?.trim()&&/^9\d{8}$/.test(m.phone||''))&&'Yape o Plin con datos completos'].filter(Boolean);
 async function persist(){
  if(!values.title.trim())throw Error('Escribe el nombre para guardar el borrador.');
  let imageId=values.primaryImageFileId;
  if(image){imageId=(await upload(image,'public')).id;setValues(v=>({...v,primaryImageFileId:imageId}));setImage(null);}
  let routeId=values.routeImageFileId;
  if(routeImage){routeId=(await upload(routeImage,'public')).id;setValues(v=>({...v,routeImageFileId:routeId}));setRouteImage(null);}
  const body={meetingAt:isoDate(meetingAt),kitEnabled:values.kitEnabled,kitDateFrom:values.kitDateFrom||null,kitDateTo:values.kitDateTo||null,kitTimeFrom:values.kitTimeFrom||null,kitTimeTo:values.kitTimeTo||null,kitVenue:values.kitVenue,kitAddress:null,kitInstructions:values.kitInstructions,routeImageFileId:routeId,title:values.title,description:values.description,venue:values.venue,startsAt:event?.lifecycle?.conditionsLocked?event.startsAt:isoDate(startsAt),timeZone:event?.lifecycle?.conditionsLocked?event.timeZone:'America/Lima',maxCapacity:Number(values.maxCapacity),disciplineId:values.disciplineId||null,primaryImageFileId:imageId};
  const saved=await api('/events/mine'+(event?.id?'/'+event.id:''),event?.id?'PATCH':'POST',body);setEvent(saved);
  if(editable){
   let rows=withCategories?categories:[...(categories.filter(c=>c.name!=='Inscripción general').map(c=>({...c,active:false}))),...(categories.some(c=>c.name==='Inscripción general')||Number(generalPrice)>0?[{...(categories.find(c=>c.name==='Inscripción general')||{key:crypto.randomUUID()}),name:'Inscripción general',price:generalPrice,active:true}]:[])];
   for(const c of rows){if(!c.name?.trim())throw Error('Completa el nombre de la categoría. La información del evento ya se guardó.');const data={name:c.name,description:c.description||null,priceCents:Math.round(Number(c.price||0)*100),currency:c.currency||'PEN',active:withCategories?c.active!==false:c.name==='Inscripción general',capacity:c.capacity??null,gender:c.gender??null,minAge:c.minAge??null,maxAge:c.maxAge??null,modality:c.modality??null};const result=await api('/events/'+saved.id+'/categories'+(c.id?'/'+c.id:''),c.id?'PUT':'POST',data);rows=rows.map(row=>row.key===c.key?{...row,id:result.id}:row);setCategories(rows);}
   const selected=[];
   for(const m of methods){if(!m.enabled){continue;}const complete=!!m.holderName?.trim()&&/^9\d{8}$/.test(m.phone||'');let qrFileId=m.qrFileId||null;if(m.file){qrFileId=(await upload(m.file,'private')).id;setMethods(all=>all.map(row=>row.key===m.key?{...row,qrFileId,file:null}:row));}const data={type:m.type,label:m.label|| (m.type==='YAPE'?'Yape':'Plin'),phone:m.phone,holderName:m.holderName,currency:'PEN',qrFileId,active:complete,instructions:m.instructions||null};const result=await api('/events/'+saved.id+'/payment-methods'+(m.id?'/'+m.id:''),m.id?'PUT':'POST',data);setMethods(all=>all.map(row=>row.key===m.key?{...row,id:result.id,qrFileId,file:null}:row));if(paid&&complete)selected.push(result.id);}
   await api('/events/'+saved.id+'/payment-methods','PUT',{methodIds:selected});
  }
  setDirty(false);dirtyRef.current=false;return saved;
 }
 function save(next){action.run(async()=>{const saved=await persist();if(next)setStep(next);if(!id)navigate('/mis-eventos/'+saved.id+'/editar?paso='+(next||step)+'&guardado=1',{replace:true});},event?.status==='PUBLISHED'?'Cambios guardados.':'Borrador guardado.');}
 if(loadError)return <section className="event-editor"><p role="alert">{loadError}</p><a href="/mis-eventos">Volver a Mis eventos</a></section>;
 if(!loaded)return <p role="status">Cargando evento…</p>;
 const conditionsLocked=event?.lifecycle?.conditionsLocked||hasRegistrations;
 const locked=event?.status==='PUBLISHED'||!editable;
 return <section className="event-editor"><header><a href="/mis-eventos">← Mis eventos</a><h1>{event?.id?'Editar evento':'Crear evento'}</h1><Status value={event?.status||'DRAFT'} label={event?.lifecycle?.displayLabel}/><p>{event?.status==='PUBLISHED'?'El evento está publicado. Puedes actualizar la información permitida.':'Este evento está en borrador y no aparece en el Home.'}</p>{event?.lifecycle?.started&&<p>La fecha de inicio ya se alcanzó. Conserva el historial y gestiona los inscritos; no se permite publicar ni despublicar.</p>}{hasRegistrations&&<p>Ya hay inscripciones: fecha, cupo, categorías y precios quedan fijos para conservar lo acordado con los participantes.</p>}</header>
 <nav className="event-editor-steps" aria-label="Pasos del evento">{['Información','Inscripciones y pagos','Revisar y publicar'].map((label,i)=><button type="button" key={label} disabled={action.busy} aria-label={`Paso ${i+1}: ${label}`} title={label} aria-current={step===i+1?'step':undefined} onClick={()=>setStep(i+1)}>{i+1}</button>)}</nav>
 <Feedback state={action}/>{event?.status!=='PUBLISHED'&&!dirty&&new URLSearchParams(location.search).get('guardado')==='1'&&<p role="status">Borrador guardado.</p>}<form noValidate onSubmit={e=>{e.preventDefault();save(step<3?step+1:undefined);}}><fieldset disabled={action.busy}>
 {step===1&&<div className="event-editor-section"><h2>Información del evento</h2><Field label="Nombre del evento" name="title" value={values.title} disabled={conditionsLocked} onChange={change} maxLength={180} required/><State resource={disciplines}>{items=><label>Disciplina<select aria-label="Disciplina" name="disciplineId" value={values.disciplineId} onChange={change} disabled={locked}><option value="">Selecciona una disciplina</option>{items.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}</State><Textarea label="Descripción" name="description" value={values.description} onChange={change} maxLength={10000}/><div className="form-grid"><Field label="Fecha del evento" name="eventDate" type="date" value={values.eventDate} onChange={change} disabled={conditionsLocked}/><Field label="Ubicación del evento" name="venue" value={values.venue} onChange={change} maxLength={500}/><Field label="Hora de concentración" name="meetingTime" type="time" value={values.meetingTime} onChange={change}/><Field label="Hora de salida" name="departureTime" type="time" value={values.departureTime} onChange={change} disabled={conditionsLocked}/></div><ImagePicker label="Imagen del evento" fileId={values.primaryImageFileId} file={image} onChange={file=>{setImage(file);setDirty(true);}}/>
<div className="event-editor-kits"><label className="check"><input type="checkbox" checked={values.kitEnabled} onChange={e=>{setValues(v=>({...v,kitEnabled:e.target.checked}));setDirty(true);}}/>Mi evento tiene entrega de kits</label>{values.kitEnabled&&<><div className="form-grid"><Field label="Fecha desde" name="kitDateFrom" type="date" value={values.kitDateFrom} onChange={change}/><Field label="Fecha hasta" name="kitDateTo" type="date" value={values.kitDateTo} onChange={change}/><Field label="Hora desde (hora de Lima)" name="kitTimeFrom" type="time" value={values.kitTimeFrom} onChange={change}/><Field label="Hora hasta (hora de Lima)" name="kitTimeTo" type="time" value={values.kitTimeTo} onChange={change}/></div><p>Horario de atención diario durante las fechas indicadas.</p><Field label="Lugar de entrega" name="kitVenue" value={values.kitVenue} maxLength={500} onChange={change}/><Textarea label="Instrucciones adicionales" name="kitInstructions" value={values.kitInstructions} maxLength={2000} onChange={change}/></>}</div>
<details className="event-editor-optional"><summary>Ruta del evento · opcional</summary><p>Agrega una imagen del recorrido para los participantes.</p><ImagePicker label="Imagen de la ruta" fileId={values.routeImageFileId} file={routeImage} onChange={file=>{setRouteImage(file);setDirty(true);}}/>{(values.routeImageFileId||routeImage)&&<button type="button" className="secondary" onClick={()=>{setValues(v=>({...v,routeImageFileId:null}));setRouteImage(null);setDirty(true);}}>Quitar imagen de ruta</button>}</details></div>}
 {step===2&&<div className="event-editor-section"><h2>Inscripciones y pagos</h2><Field label="Cupo máximo" name="maxCapacity" type="number" min={1} max={1000000} value={values.maxCapacity} onChange={change} disabled={conditionsLocked||!editable}/>{!editable&&<div className="event-editor-missing">{event?.lifecycle?.started?<p>La fecha de inicio ya se alcanzó. Categorías, precios y medios de pago permanecen fijos.</p>:hasRegistrations?<><p>Este evento ya tiene inscripciones. No se pueden modificar sus categorías, precios ni medios de pago, aunque esté despublicado.</p><a className="button secondary" href="/mis-eventos/nuevo">Crear otro evento</a></>:event?.status==='PUBLISHED'?<p>Despublica el evento desde Mis eventos para configurar los precios y pagos. Se permite mientras no tenga inscripciones.</p>:<p>La configuración de inscripciones está bloqueada por el estado del evento.</p>}</div>}<label>¿Tu evento tiene categorías o distancias?<select value={withCategories?'yes':'no'} disabled={!editable} onChange={e=>{setWithCategories(e.target.value==='yes');setDirty(true);}}><option value="no">No, inscripción general</option><option value="yes">Sí, por categorías o distancias</option></select></label>
 {withCategories?<>{categories.map(c=><div className="event-editor-category" key={c.key}><Field label="Nombre de categoría o distancia" value={c.name} maxLength={160} disabled={!editable} onChange={e=>updateCategory(c.key,{name:e.target.value})}/><Field label="Precio en soles (0 = gratis)" type="number" min={0} max={20000000} step="0.01" value={c.price} disabled={!editable} onChange={e=>updateCategory(c.key,{price:e.target.value})}/><label className="check"><input type="checkbox" checked={c.active!==false} disabled={!editable} onChange={e=>updateCategory(c.key,{active:e.target.checked})}/>Activa</label>{!c.id&&<button type="button" className="secondary" disabled={!editable} onClick={()=>{setCategories(rows=>rows.filter(row=>row.key!==c.key));setDirty(true);}}>Quitar categoría</button>}</div>)}<button type="button" className="secondary" disabled={!editable} onClick={()=>{setCategories(all=>[...all,{key:crypto.randomUUID(),name:'',price:'0',active:true}]);setDirty(true);}}>Agregar categoría</button></>:<Field label="Precio de inscripción en soles (0 = gratis)" type="number" min={0} max={20000000} step="0.01" value={generalPrice} disabled={!editable} onChange={e=>{setGeneralPrice(e.target.value);setDirty(true);}}/>}
 {paid?<><h3>Medios de pago aceptados</h3><p>El participante paga y adjunta su comprobante. Tú verificas la inscripción.</p>{['YAPE','PLIN'].map(type=>{const m=methods.find(row=>row.type===type)||{key:type,type,enabled:false,holderName:'',phone:''};return <div className="event-editor-payment" key={type}><label className="check"><input type="checkbox" checked={m.enabled} disabled={!editable} onChange={e=>{if(methods.some(row=>row.key===m.key))updateMethod(m.key,{enabled:e.target.checked});else{setMethods(all=>[...all,{...m,enabled:e.target.checked}]);setDirty(true);}}}/>{type==='YAPE'?'Yape':'Plin'}</label>{m.enabled&&<><Field label="Nombre del receptor" value={m.holderName||''} maxLength={120} disabled={!editable} onChange={e=>updateMethod(m.key,{holderName:e.target.value})}/><Field label="Celular peruano (9 dígitos)" type="tel" value={m.phone||''} maxLength={9} disabled={!editable} onChange={e=>updateMethod(m.key,{phone:e.target.value})}/><ImagePicker label={'QR de '+type+' (opcional)'} privateFile fileId={m.qrFileId} file={m.file} disabled={!editable} onChange={file=>updateMethod(m.key,{file})}/></>}</div>;})}</>:<p>Evento gratuito: no necesitas configurar pagos.</p>}</div>}
 {step===3&&<div className="event-editor-section"><h2>Revisar y publicar</h2><h3>{values.title||'Evento sin nombre'}</h3><p>{values.description||'Descripción pendiente'}</p><p>{startsAt?new Intl.DateTimeFormat('es-PE',{dateStyle:'long',timeStyle:'short',timeZone:'America/Lima'}).format(new Date(startsAt+'-05:00'))+' · Lima':'Fecha por definir'} · {values.venue||'Ubicación pendiente'}</p><p>Cupo: {values.maxCapacity}</p>{activeCategories.map((c,i)=><p key={i}>{c.name||'Categoría sin nombre'} · {money(Math.round(Number(c.price||0)*100))}</p>)}{paid&&<p>Pago: {methods.filter(m=>m.enabled).map(m=>m.type+' · '+(m.holderName||'Receptor pendiente')+' · '+(m.phone||'Celular pendiente')).join(' / ')||'Pendiente'}</p>}<ImagePicker label="Imagen del evento" fileId={values.primaryImageFileId} file={image} onChange={file=>{setImage(file);setDirty(true);}}/>{values.meetingTime&&<p>Concentración: {values.meetingTime}</p>}{values.kitEnabled&&<div><h3>Entrega de kits</h3><p>{values.kitDateFrom||'Fecha pendiente'} — {values.kitDateTo||'Fecha pendiente'}</p><p>Horario diario: {values.kitTimeFrom||'Hora pendiente'} — {values.kitTimeTo||'Hora pendiente'}</p><p>{values.kitVenue||'Lugar pendiente'}</p>{values.kitInstructions&&<p className="preline">{values.kitInstructions}</p>}</div>}{(values.routeImageFileId||routeImage)&&<ImagePicker label="Ruta del evento" fileId={values.routeImageFileId} file={routeImage} onChange={file=>{setRouteImage(file);setDirty(true);}}/>}<div className="event-editor-review-links"><button type="button" className="secondary" onClick={()=>setStep(1)}>Editar información</button><button type="button" className="secondary" onClick={()=>setStep(2)}>Editar inscripciones y pagos</button></div>{missing.length>0&&<div className="event-editor-missing"><strong>Completa antes de publicar:</strong><ul>{missing.map(item=><li key={item}>{item}</li>)}</ul></div>}{event?.status!=='PUBLISHED'&&<button type="button" className="event-editor-publish" disabled={action.busy||missing.length>0||!!event?.lifecycle?.publicationBlockReason} onClick={()=>action.run(async()=>{const saved=await persist();await api('/events/mine/'+saved.id+'/publish','POST',{});navigate('/mis-eventos');},'Evento publicado.')}>Publicar evento</button>}</div>}
 <div className="event-editor-footer"><IconAction label={event?.status==='PUBLISHED'?'Guardar cambios':'Guardar borrador'} icon="save" onClick={()=>save()} disabled={action.busy}/>{step>1&&<IconAction label="Anterior" icon="previous" onClick={()=>setStep(step-1)} disabled={action.busy}/ >}{step<3&&<IconAction label="Continuar" icon="next" type="submit" disabled={action.busy}/>}</div></fieldset></form></section>;
}
