import {Modal,ActionIcon} from '../components/Modal.jsx';
import {EventForm} from '../components/EventForm.jsx';
export {EventForm} from '../components/EventForm.jsx';
import React,{useState}from'react';import{api,upload,fileUrl}from'../services/api.js';import{useData,useAction}from'../hooks/data.js';import{State,Feedback,Field,Textarea,Records,Status,date,money}from'../components/UI.jsx';
export function ManageEvents({user,resource:r,scope="INVICTUS"}) {
 const [filter,setFilter]=useState('PENDING_REVIEW');
 const a=useAction(),[editing,setEditing]=useState(null),[attendees,setAttendees]=useState(null),[reviewing,setReviewing]=useState(null),[note,setNote]=useState('');
 const admin=user?.role==='ADMIN';
 const external=scope==='EXTERNAL';
 const filters=[['PENDING_REVIEW','Pendientes'],['CHANGES_REQUESTED','Cambios solicitados'],['APPROVED','Aprobados'],['ALL','Todos']];
 return <><p>{external?'Revisa las propuestas de organizadores externos, apruébalas o solicita cambios.':'Crea y administra los eventos organizados por Invictus.'}</p>
 {external&&<div className="actions event-review-filters" role="group" aria-label="Filtrar eventos externos">{filters.map(([value,label])=><button key={value} className="secondary" aria-pressed={filter===value} onClick={()=>{setFilter(value);setReviewing(null);setAttendees(null);}}>{label}{!r.loading&&!r.error&&` (${(r.data||[]).filter(e=>e.source==='EXTERNAL'&&e.reviewStatus!=='DRAFT'&&(value==='ALL'||e.reviewStatus===value)).length})`}</button>)}</div>}
 {admin&&!external&&<button onClick={()=>{setEditing({});setReviewing(null);setAttendees(null)}}>Crear evento Invictus +</button>}
 <Feedback state={a}/>
 {editing&&<EventForm key={editing.id||'new'} event={editing} close={()=>setEditing(null)} saved={()=>{setEditing(null);r.reload()}}/>}
 {reviewing&&<section className="card detail"><h2>Revisar: {reviewing.title}</h2><p className="preline">{reviewing.description}</p><p>{date(reviewing.startsAt)} · {reviewing.venue} · Cupo: {reviewing.configuration?.maxCapacity}</p>
 {reviewing.primaryImageFileId&&<img src={fileUrl(reviewing.primaryImageFileId)} alt="Imagen del evento"/>}
 <Textarea label="Observaciones para el organizador" value={note} maxLength="2000" onChange={e=>setNote(e.target.value)}/>
 <div className="actions"><button disabled={a.busy} onClick={()=>a.run(async()=>{await api(`/events/manage/${reviewing.id}/review`,'POST',{decision:'APPROVE'});setReviewing(null);r.reload();},'Evento aprobado y publicado.')}>Aprobar y publicar</button>
 <button className="secondary" disabled={a.busy||!note.trim()} onClick={()=>a.run(async()=>{await api(`/events/manage/${reviewing.id}/review`,'POST',{decision:'REQUEST_CHANGES',note});setReviewing(null);r.reload();},'Observaciones enviadas al organizador.')}>Solicitar cambios</button>
 <button className="secondary" disabled={a.busy} onClick={()=>setReviewing(null)}>Cerrar</button></div></section>}
 <State resource={r}>{items=>{const visible=items.filter(i=>external?i.source==='EXTERNAL'&&i.reviewStatus!=='DRAFT'&&(filter==='ALL'||i.reviewStatus===filter):i.source!=='EXTERNAL');return visible.length?<Records items={visible} columns={[{label:'Evento',render:i=>i.title},{label:'Team',render:i=>i.team?.name||'Pendiente de asignación'},{label:'Fecha',render:i=>date(i.startsAt)},{label:'Estado',render:i=><Status value={i.source==='EXTERNAL'&&i.status==='DRAFT'?i.reviewStatus:i.status}/>}]} actions={i=><>
 {admin&&i.canManage&&i.source!=='EXTERNAL'&&<><button className="secondary icon-action" aria-label="Editar evento" title="Editar evento" disabled={a.busy} onClick={()=>a.run(async()=>{setReviewing(null);setEditing(await api('/events/manage/'+i.id));},'')}><ActionIcon name="edit"/></button>{i.status==='DRAFT'&&<button disabled={a.busy} onClick={()=>a.run(async()=>{await api(`/events/manage/${i.id}/publish`,'POST',{});r.reload()},'Evento publicado.')}>Publicar</button>}</>}
 {admin&&i.source==='EXTERNAL'&&i.reviewStatus==='PENDING_REVIEW'&&<button disabled={a.busy} onClick={()=>a.run(async()=>{setEditing(null);setNote('');setReviewing(await api('/events/manage/'+i.id));},'')}>Revisar evento</button>}
 {i.canManage&&<button className="secondary icon-action" aria-label="Ver inscritos" title="Ver inscritos" onClick={()=>setAttendees(i)}><ActionIcon name="people"/></button>}</>}/>:<p className="empty">{external?(filter==='PENDING_REVIEW'?'No hay eventos pendientes de revisión.':'No hay eventos en este filtro.'):'Todavía no hay eventos de Invictus. Crea el primero para comenzar.'}</p>;}}</State>{attendees&&<Attendees key={attendees.id} event={attendees} close={()=>setAttendees(null)}/>}</>;
}
export function Attendees({event,close,endpoint='/events/manage'}){const r=useData(`${endpoint}/${event.id}/attendees`);return <Modal title={`Inscritos · ${event.title}`} onClose={close}><State resource={r}>{items=>items.length?<Records items={items} columns={[{label:'Participante',render:i=>`${i.participant?.name||''} ${i.participant?.lastName||''}`},{label:'Correo',render:i=>i.participant?.email},{label:'Estado',render:i=><Status value={i.status}/>}]}/>:<p className="empty">Todavía no hay inscritos en este evento.</p>}</State></Modal>}
export function Products(){const r=useData('/shop/admin/products'),[editing,setEditing]=useState(null);return <><p>Estos productos representan existencias físicas. Los encargos personalizados se reciben en Cotizaciones.</p><button onClick={()=>setEditing({})}>Crear producto +</button>{editing&&<ProductForm key={editing.id||'new'} product={editing} close={()=>setEditing(null)} saved={()=>{setEditing(null);r.reload()}}/>}<State resource={r}>{items=><Records items={items} columns={[{label:'Producto',render:i=>i.name},{label:'Precio base',render:i=>money(i.priceCents)},{label:'Existencias',render:i=>i.variants.reduce((n,v)=>n+v.stock,0)},{label:'Visibilidad',render:i=>i.published?'Publicado':'Borrador'}]} actions={i=><button className="secondary" onClick={()=>setEditing(i)}>Editar</button>}/>}</State></>}
function ProductForm({product:p,close,saved}){const a=useAction(),[image,setImage]=useState(null),[variants,setVariants]=useState(p.variants||[{name:'Estándar',sku:'',priceCents:1000,stock:1}]);return <form className="form card detail" onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));v.priceCents=Math.round(Number(v.price)*100);delete v.price;v.published=v.published==='on';v.variants=variants.map(x=>({...x,stock:Number(x.stock),priceCents:Number(x.priceCents)}));a.run(async()=>{if(image)v.imageFileId=(await upload(image,'public')).id;await api('/shop/admin/products'+(p.id?'/'+p.id:''),p.id?'PATCH':'POST',v);saved()},'Producto guardado.')}}><h2>{p.id?'Editar producto':'Nuevo producto'}</h2><Field label="Nombre" name="name" defaultValue={p.name} required/><Textarea label="Descripción" name="description" defaultValue={p.description} required/><Field label="Precio base en soles" name="price" type="number" min="0.01" max="100000" step="0.01" defaultValue={(p.priceCents||1000)/100} required/><label className="check"><input type="checkbox" name="published" defaultChecked={p.published}/> Publicar en el catálogo</label><label>Imagen pública (PNG/JPG/WebP, hasta 10 MB)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setImage(e.target.files[0])}/></label><h3>Variantes y existencias físicas</h3>{variants.map((v,i)=><fieldset className="form-grid" key={v.id||i}><legend>Variante {i+1}</legend>{[['name','Nombre','text'],['sku','SKU','text'],['stock','Existencias','number'],['priceCents','Precio en céntimos','number']].map(([key,label,type])=><Field key={key} label={label} type={type} min={key==='priceCents'?1:0} value={v[key]} required onChange={e=>setVariants(variants.map((x,j)=>i===j?{...x,[key]:e.target.value}:x))}/>)}</fieldset>)}<button type="button" className="secondary" onClick={()=>setVariants([...variants,{name:'',sku:'',priceCents:1000,stock:0}])}>Añadir variante</button><p className="muted">No se pueden editar productos con reservas activas.</p><div className="actions"><button disabled={a.busy}>Guardar producto</button><button type="button" className="secondary" onClick={close}>Volver</button></div><Feedback state={a}/></form>}
export function Quotes(){const r=useData('/admin/quotes');return <State resource={r}>{items=><Records items={items} columns={[{label:'Contacto',render:i=><>{i.contactName}<br/>{i.email}<br/>{i.phone}</>},{label:'Solicitud',render:i=><>{i.quantity} unidades<br/>{i.design}</>},{label:'Fecha requerida',render:i=>date(i.requiredDate)},{label:'Estado',render:i=><Status value={i.status}/>}]}/>}</State>}
export function Users(){const r=useData('/admin/users'),a=useAction();return <><p>Los registros públicos se crean como participantes. Concede el rol de organizador solo a personas autorizadas.</p><Feedback state={a}/><State resource={r}>{items=><Records items={items} columns={[{label:'Persona',render:i=>`${i.name} ${i.lastName}`},{label:'Correo',render:i=>i.email},{label:'Rol',render:i=>({USER:'Participante',ORGANIZER:'Organizador',ADMIN:'Administrador'})[i.role]}]} actions={i=><select aria-label={'Rol de '+i.name} value={i.role} disabled={a.busy} onChange={e=>{const role=e.target.value;if(confirm('¿Cambiar los permisos de esta persona?'))a.run(async()=>{await api(`/admin/users/${i.id}/role`,'PATCH',{role});r.reload()},'Rol actualizado.')}}><option value="USER">Participante</option><option value="ORGANIZER">Organizador</option><option value="ADMIN">Administrador</option></select>}/>}</State></>}
