import {EventDetail} from '../components/EventDetail.jsx';
import {navigate} from '../services/navigation.js';
import '../styles/public-shop.css';
import '../styles/public-events.css';
import React,{useState}from'react';import{api,fileUrl}from'../services/api.js';import{useData,useAction}from'../hooks/data.js';import{Heading,State,Feedback,date,money,Field,Textarea}from'../components/UI.jsx';
import {GuestEnrollment} from '../components/GuestRegistration.jsx';
import {EventCards} from '../components/EventCards.jsx';
import {CategoryEnrollment} from '../components/CategoryRegistration.jsx';
export {default as Home} from './Landing.jsx';
export function Events({slug,user}) {
 const r=useData(slug?'/events/public/'+slug:'/events');
 return slug?<section className="public-events event-single"><State resource={r}>{data=><EventDetail key={data.id} event={data} user={user}/>}</State></section>:<section className="public-events"><Heading eyebrow="ENCUENTRA TU PRÓXIMO DESAFÍO" title={<>Eventos para <em>darlo todo.</em></>}><p>Encuentra tu próximo reto y conecta con la comunidad deportiva.</p></Heading><State resource={r}>{data=>data.length?<EventCards events={data}/>:<p className="empty">Estamos preparando los próximos eventos. Vuelve pronto.</p>}</State></section>;
}
export function Quote(){const a=useAction();return <><Heading eyebrow="DISEÑADO PARA TU EVENTO" title="Un reconocimiento tan único como tu esfuerzo."><p>Fabricación por encargo, sujeta a cotización. Esta solicitud no genera un pedido ni reserva existencias.</p></Heading><form className="form card" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;const v=Object.fromEntries(new FormData(f));v.quantity=Number(v.quantity);a.run(async()=>{const r=await api('/quotes','POST',v);f.reset();return r},'Solicitud recibida. Te contactaremos para revisar el diseño y la fecha.')}}><div className="form-grid"><Field label="Nombre de contacto" name="contactName" required maxLength="120"/><Field label="Correo electrónico" name="email" type="email" required/><Field label="Teléfono" name="phone" required minLength="6"/><Field label="Cantidad" name="quantity" type="number" min="1" max="100000" required/><Field label="Fecha requerida" name="requiredDate" type="date" min={new Date().toISOString().slice(0,10)} required/></div><Textarea label="Cuéntanos el diseño, el tipo de reconocimiento y los detalles de tu evento" name="design" required minLength="10" maxLength="5000"/><button disabled={a.busy}>Solicitar cotización →</button><Feedback state={a}/></form></>}
export function Shop({user,cart,setCart}){const r=useData('/shop/catalog'),a=useAction();return <section className="public-shop"><Heading eyebrow="RECONOCIMIENTOS 3D" title={<>El esfuerzo <em>toma forma.</em></>}><p>Trofeos, medallas y reconocimientos. Existencias físicas listas para comprar.</p></Heading><Feedback state={a}/><State resource={r}>{products=>products.length?<div className="grid">{products.map(p=><Product key={p.id} p={p} busy={a.busy} add={(variant,quantity)=>a.run(async()=>{if(!user){navigate('/acceso');return;}const previous=cart?.items||[];const found=previous.find(i=>i.variantId===variant);const items=[...previous.filter(i=>i.variantId!==variant).map(({productId,variantId,quantity})=>({productId,variantId,quantity})),{productId:p.id,variantId:variant,quantity:quantity+(found?.quantity||0)}];setCart(await api('/shop/cart','POST',{cartId:cart?.cartId,items}));},'Añadido al carrito.')}/>)}</div>:<p className="empty">El catálogo estará disponible pronto. También puedes solicitar un diseño personalizado.</p>}</State><aside className="callout"><h2>¿Buscas algo personalizado?</h2><p>Cuéntanos tu idea, cantidad y fecha requerida.</p><a href="/cotizar" className="button secondary">Solicitar cotización ↗</a></aside></section>}
function Product({p,add,busy}){const[v,setV]=useState(p.variants[0]?.id),[q,setQ]=useState(1);const variant=p.variants.find(x=>x.id===v);return <article className="card shop-product"><div className="product-cover">{p.imageFileId?<img src={fileUrl(p.imageFileId)} alt={p.name} loading="lazy"/>:<span aria-hidden="true">◇</span>}</div><h2>{p.name}</h2><p>{p.description}</p><label>Variante<select value={v} onChange={e=>setV(e.target.value)}>{p.variants.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><strong className="price">{money(variant?.priceCents||p.priceCents)}</strong><p>{variant?.stock||0} unidades disponibles</p><Field label="Cantidad" type="number" min="1" max={Math.min(99,variant?.stock||1)} value={q} onChange={e=>setQ(Number(e.target.value))}/><button disabled={busy||!variant?.stock||q<1||q>variant.stock} onClick={()=>add(v,q)}>Añadir al carrito +</button></article>}
