import express from 'express';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import { rateLimit } from 'express-rate-limit';
import { createAuthService,createAuthMiddleware,createAuthRouter,sessionCookieOptions,AppError } from '@base/usuarios-acceso';
import { createFileService,createFileRouter,createPrismaFileRepository,createLocalStorage,createS3Storage } from '@base/archivos-imagenes';
import { createOrderRouter } from '@base/pedidos';
import { createPaymentRouter } from '@base/pagos-manuales';
import { createStoreRouter } from '@base/tienda-virtual';
import { createPanelAccess } from '@base/panel-administrativo';
import { composeServices } from './services.js';
import { resolvePermissions } from './permissions.js';
import { createQuoteService } from './quotes.js';
export async function createApp({database,Prisma,config}) {
 const app=express();app.disable('x-powered-by');app.set('trust proxy',config.TRUST_PROXY);
 app.use(cors({origin:(origin,done)=>done(null,!origin||config.origins.includes(origin)),credentials:true}));
 app.use('/api',(req,res,next)=>{res.set({'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});if(!['GET','HEAD','OPTIONS'].includes(req.method)){if(!config.origins.includes(req.get('origin')))return next(new AppError('Origen no permitido',403,'INVALID_ORIGIN'));if(!(req.method==='POST'&&req.path==='/files')&&!req.is('application/json'))return next(new AppError('Formato no admitido',415,'JSON_REQUIRED'));}next();});
 app.use((req,res,next)=>req.method==='POST'&&req.path==='/api/files'?next():express.json({limit:'64kb'})(req,res,next));app.use(cookieParser());
 const authService=createAuthService({database});const cookieOptions=sessionCookieOptions({secure:config.NODE_ENV==='production'});
 const authOptions={authService,cookieName:config.NODE_ENV==='production'?'__Host-invictus_session':'invictus_session',cookieOptions};const auth=createAuthMiddleware(authOptions);
 app.use('/api/auth',createAuthRouter({...authOptions,authMiddleware:auth}));
 const storage=config.STORAGE_DRIVER==='s3'?await createS3Storage({bucket:config.S3_BUCKET,region:config.AWS_REGION}):createLocalStorage({directory:config.UPLOAD_DIRECTORY});
 const files=createFileService({repository:createPrismaFileRepository(database),storage,signingKey:config.FILE_SIGNING_KEY});
 const s=composeServices({database,Prisma,files,config});const quotes=createQuoteService(database);
 app.get('/api/health',async(req,res)=>{await database.$queryRaw`SELECT 1`;res.json({status:'ok'});});
 app.use('/api/files',createFileRouter({service:files,requireAuth:auth.requireAuth}));
 app.use('/api/panel',createPanelAccess({resolvePermissions}).router({requireAuth:auth.requireAuth}));
 app.get('/api/events',async(req,res)=>res.json(await s.events.publicList()));
 app.get('/api/events/public/:slug',async(req,res)=>res.json(await s.events.detail(req.params.slug)));
 app.get('/api/events/manage',auth.requireAuth,async(req,res)=>res.json(await s.events.list(req.user)));
 app.get('/api/events/manage/:id',auth.requireAuth,async(req,res)=>res.json(await s.events.managed(req.user,req.params.id)));
 app.post('/api/events/manage',auth.requireAuth,async(req,res)=>res.status(201).json(await s.events.save(req.user,null,req.body)));
 app.patch('/api/events/manage/:id',auth.requireAuth,async(req,res)=>res.json(await s.events.save(req.user,req.params.id,req.body)));
 app.post('/api/events/manage/:id/publish',auth.requireAuth,async(req,res)=>res.json(await s.events.publish(req.user,req.params.id)));
 app.get('/api/events/manage/:id/attendees',auth.requireAuth,async(req,res)=>res.json(await s.events.attendees(req.user,req.params.id)));
 app.post('/api/events/:id/register',auth.requireAuth,async(req,res)=>res.status(201).json(await s.events.enroll(req.user,req.params.id)));
 app.get('/api/profile',auth.requireAuth,async(req,res)=>res.json(await s.profiles.getMine(req.user)));
 app.put('/api/profile',auth.requireAuth,async(req,res)=>res.json(await s.profiles.save(req.user,req.body)));
 app.get('/api/profile/registrations',auth.requireAuth,async(req,res)=>res.json(await s.events.history(req.user)));
 app.use('/api/shop',(req,res,next)=>req.method==='GET'&&req.path==='/catalog'?next():auth.requireAuth(req,res,next),createStoreRouter({service:s.shop}));
 app.use('/api/orders',createOrderRouter({service:s.checkout,requireAuth:auth.requireAuth}));
 app.use('/api/payments',createPaymentRouter({service:s.payments,recipients:s.recipients,requireAuth:auth.requireAuth}));
 app.post('/api/quotes',rateLimit({windowMs:3600000,limit:20}),async(req,res)=>res.status(201).json(await quotes.create(null,req.body)));
 app.get('/api/admin/quotes',auth.requireAuth,async(req,res)=>res.json(await quotes.list(req.user)));
 app.get('/api/admin/users',auth.requireAuth,async(req,res)=>res.json(await s.users.list(req.user)));
 app.patch('/api/admin/users/:id/role',auth.requireAuth,async(req,res)=>res.json(await s.users.role(req.user,req.params.id,req.body.role)));
 app.use((req,res)=>res.status(404).json({error:{code:'NOT_FOUND',message:'No encontrado'}}));
 app.use((error,req,res,next)=>{if(res.headersSent)return next(error);const status=error.status||error.statusCode||400*(error.name==='ZodError')||500;const known=status<500; if(!known)console.error(JSON.stringify({event:'request_failed',code:error.code||error.name}));res.status(status).json({error:{code:known?error.code||'INVALID_INPUT':'INTERNAL_ERROR',message:known?error.message:'No pudimos completar la solicitud. Intenta nuevamente.'}});});
 return app;
}
