import { chromium } from '@playwright/test';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import { mkdir,writeFile } from 'node:fs/promises';
import { PrismaClient,Prisma } from '../prisma/client/index.js';
import { readConfig } from '../server/config.js';
import { createApp } from '../server/app.js';
import { randomUUID } from 'node:crypto';
const url=new URL(process.env.TEST_DATABASE_URL);if(url.hostname!=='localhost'||url.pathname!=='/invictus_test')throw new Error('Solo invictus_test local');
const db=new PrismaClient({datasources:{db:{url:url.href}}});const origin='http://localhost:5174',adminOrigin='http://localhost:5176';const recipientId=randomUUID();const config=readConfig({...process.env,DATABASE_URL:url.href,WEB_ORIGINS:origin+','+adminOrigin,PUBLIC_WEB_URL:origin,UPLOAD_DIRECTORY:'.local/browser-uploads',PAYMENT_RECIPIENT_ID:recipientId,PAYMENT_METHODS:'cash',NODE_ENV:'test'});
const app=await createApp({database:db,Prisma,config});const server=app.listen(3101);const vite=await createServer({configFile:false,root:'client',plugins:[react()],define:{'import.meta.env.VITE_ADMIN_URL':JSON.stringify(adminOrigin)},server:{host:'localhost',port:5174,strictPort:true,proxy:{'/api':'http://localhost:3101'}}});await vite.listen();const adminVite=await createServer({configFile:false,root:'admin',publicDir:'../client/public',plugins:[react()],define:{'import.meta.env.VITE_PUBLIC_URL':JSON.stringify(origin)},server:{host:'localhost',port:5176,strictPort:true,proxy:{'/api':'http://localhost:3101'},fs:{allow:['..']}}});await adminVite.listen();
let browser;const errors=[];await mkdir('.local/screenshots',{recursive:true});
try{
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 const adminEmail=`browser-admin-${randomUUID()}@example.test`,participantEmail=`browser-user-${randomUUID()}@example.test`,password='Invictus-Test-2026!';
 async function register(email){await page.goto(origin+'/?entry='+randomUUID()+'#/acceso');await page.getByRole('button',{name:'Crear una cuenta',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill('Prueba');await page.getByLabel('Apellidos').fill('Invictus');await page.getByLabel('Correo electrónico').fill(email);await page.getByLabel('Contraseña').fill(password);await page.getByRole('button',{name:'Crear cuenta →',exact:true}).click();await page.getByRole('heading',{name:'Hola, Prueba.'}).waitFor();}
 async function login(email){await page.goto(origin+'/?login='+randomUUID()+'#/acceso');await page.getByLabel('Correo electrónico').fill(email);await page.getByLabel('Contraseña').fill(password);await page.getByRole('button',{name:'Iniciar sesión →',exact:true}).click();await page.getByRole('heading',{name:'Hola, Prueba.'}).waitFor();}
 await page.goto(origin);await page.getByRole('heading',{name:/Tu próximo/}).waitFor();await page.screenshot({path:'.local/screenshots/home-desktop.png',fullPage:true});
 await register(adminEmail);const admin=await db.user.update({where:{email:adminEmail},data:{role:'ADMIN'}});await db.paymentRecipient.create({data:{id:recipientId,name:'Invictus TEST VISUAL',holder:'Prueba'}});await db.recipientMember.create({data:{recipientId,userId:admin.id,manage:true,review:true}});
 await page.getByRole('button',{name:'Salir',exact:true}).click();await login(adminEmail);await page.getByRole('link',{name:'Gestión',exact:true}).click();await page.getByRole('button',{name:'Crear evento +'}).click();
 const title='EVENTO VISUAL '+randomUUID().slice(0,8);await page.getByLabel('Título',{exact:true}).fill(title);await page.getByLabel('Descripción',{exact:true}).fill('Evento identificado de prueba visual de Invictus');await page.getByLabel('Fecha y hora de Lima').fill('2027-06-20T09:00');await page.getByLabel('Lugar',{exact:true}).fill('Lima');await page.getByRole('button',{name:'Guardar evento',exact:true}).click();await page.getByRole('button',{name:'Publicar',exact:true}).last().click();await page.getByText('Evento publicado.',{exact:true}).waitFor();
 await page.getByRole('link',{name:'Productos',exact:true}).click();await page.getByRole('button',{name:'Crear producto +'}).click();await page.getByLabel('Nombre',{exact:true}).first().fill('TROFEO PRUEBA VISUAL');await page.getByLabel('Descripción',{exact:true}).fill('Trofeo de prueba visual, no disponible comercialmente');await page.getByLabel('SKU',{exact:true}).fill(randomUUID());await page.getByLabel('Publicar en el catálogo').check();await page.getByRole('button',{name:'Guardar producto',exact:true}).click();await page.getByRole('heading',{name:'Nuevo producto',exact:true}).waitFor({state:'hidden'});
 await page.getByRole('link',{name:'Eventos',exact:true}).click();await page.screenshot({path:'.local/screenshots/admin-desktop.png',fullPage:true});await page.getByRole('button',{name:'Cerrar sesión',exact:true}).click();await page.goto(origin+'/?reset='+randomUUID());
 await register(participantEmail);await page.getByRole('link',{name:'Eventos',exact:true}).click();await page.getByRole('heading',{name:title,exact:true}).click();await page.getByRole('button',{name:'Inscribirme gratis',exact:true}).click();await page.getByText('Tu inscripción está confirmada. Puedes consultarla en Mi cuenta.',{exact:true}).waitFor();await page.getByRole('link',{name:'Mi cuenta',exact:true}).click();await page.getByText(title,{exact:true}).first().waitFor();await page.screenshot({path:'.local/screenshots/account-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Reconocimientos',exact:true}).click();const product=page.getByRole('article').filter({has:page.getByRole('heading',{name:'TROFEO PRUEBA VISUAL',exact:true})}).last();await product.getByRole('button',{name:'Añadir al carrito +',exact:true}).click();await page.getByText('Añadido al carrito.',{exact:true}).waitFor();await page.getByRole('link',{name:'Carrito',exact:true}).click();await page.getByRole('button',{name:'Crear pedido →',exact:true}).click();await page.getByRole('button',{name:'Ver detalle',exact:true}).first().click();await page.getByRole('button',{name:'Registrar pago para revisión',exact:true}).click();await page.getByText('Pago registrado para revisión.',{exact:true}).waitFor();await page.screenshot({path:'.local/screenshots/order-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Salir',exact:true}).click();await login(adminEmail);await page.getByRole('link',{name:'Gestión',exact:true}).click();await page.getByRole('link',{name:'Pedidos y pagos',exact:true}).click();await page.getByRole('button',{name:'Ver detalle',exact:true}).first().click();await page.getByRole('button',{name:'Verificar pago',exact:true}).click();await page.getByText('Pago verificado.',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/screenshots/admin-mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Overflow móvil admin');
 await page.goto(origin+'/#/');await page.screenshot({path:'.local/screenshots/home-mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Overflow móvil público');
 if(errors.length)throw new Error(errors.join('; '));await writeFile('.local/browser-result.json',JSON.stringify({passed:true,flows:['registro','login','creación y publicación evento','producto','inscripción y perfil','carrito y pedido','registro y revisión pago','responsive 390 y 1440'],consoleErrors:errors},null,2));console.log('Browser E2E passed; screenshots in .local/screenshots');
}finally{await browser?.close();await vite.close();await adminVite.close();await new Promise(r=>server.close(r));await db.$disconnect();}
